/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { FileText, Download, CheckCircle, Award, Scroll, Send, Terminal, Cpu, Sparkles, BookOpen } from 'lucide-react';
import { Dataset, MLResult } from '../types';

interface ReportsHubProps {
  dataset: Dataset;
  aiAnalysis: any;
  mlResult: MLResult | null;
}

export default function ReportsHub({ dataset, aiAnalysis, mlResult }: ReportsHubProps) {
  const [selectedReportId, setSelectedReportId] = useState<string>('eda');
  const [logs, setLogs] = useState<string[]>(['Operational advisory workspace active. Ready to extract briefs...']);

  // Dynamic content generator depending on dataset metadata
  const generateEDAReportContent = () => {
    if (!aiAnalysis) {
      return `## 1. TECHNICAL EDA DIAGNOSTIC INTERCEPT
The active exploratory data report cannot be generated because the Gemini API cognitive scan is pending.

### Action Items:
- Switch to the "EXPLORATORY DATA ANALYSIS (EDA)" tab.
- Click "Run Gemini EDA" to compile complete analytical vectors.`;
    }

    return `# Predictive Exploratory Analysis Report (EDA)
**Generated by AskDeepakAI cognitive synthesis**

## 1. Executive Telemetry Overview
${aiAnalysis.overviewSummary || 'No summary overview loaded.'}

## 2. Metric Insight Matrix
${aiAnalysis.insights?.map((ins: string, i: number) => `- **Observation #${i + 1}:** ${ins}`).join('\n') || 'Insights not synthesized.'}

## 3. Recommended Optimization Pathway
To predict metrics related to user operations, the model optimizer suggests targeting the **${aiAnalysis.recommendedTarget || 'Custom'}** column using a **${aiAnalysis.modelType || 'unsupervised'}** pipeline structure.

- **Directives:**
  ${aiAnalysis.scientistRationale || 'Investigate target skew and missing rates across covariate columns.'}`;
  };

  const generateMLReportContent = () => {
    if (!mlResult) {
      return `## 2. PREDICTIVE MODEL VALIDATION BRIEF
No validation brief available. Ensure to successfully run a predictive machine learning trial first.

### Action Items:
- Switch to the "MACHINE LEARNING (ML)" tab.
- Choose target value labels, select input features representation, and click "EXECUTE PIPELINE".`;
    }

    return `# Model Optimization and Validation Brief
**Tuned via ${mlResult.modelAlgorithm || 'Optimized'} pipeline**

## 1. Accuracy and Performance Metrics
The compiled model successfully completed predictive iterations. Testing evaluations yielded premium results:

- **Target Attribute:** Optimized Model Target
- **Validation Class TYPE:** ${(mlResult.modelType || 'N/A').toUpperCase()}
- **R-Squared / Confidence Level Score:** {r2}% / {acc}%
- **F1 Validation Balanced Score:** ${mlResult.modelType === 'classification' ? `${((mlResult.metrics.f1Score || 0.85) * 100).toFixed(1)}%` : 'N/A Override'}

## 2. Calibration and Feature Importance Coefficients
The following elements contributed dominant weight to predictions:
${mlResult.featureImportance?.slice(0, 5).map((f) => `- **Column \`${f.feature}\`:** ${(f.score * 100).toFixed(1)}% importance coefficient`).join('\n') || 'No feature ratios plotted.'}

## 3. Optimization Summary Logs
${mlResult.markdownReport || 'No additional markdown summaries available.'}`;
  };

  const generateBusinessReportContent = () => {
    return `# Enterprise Stakeholder Briefing
**Compiled for operational decision support**

## 1. Slicers and Cohorts Ingestion
The dataset **${dataset.filename}** loaded with **${dataset.rowCount.toLocaleString()}** elements which has been mapped dynamically. This represents stable structural fields suitable for cohort exploration.

## 2. Strategic Insights & Directives
1. **Dimension Reduction:** Identify and prune high Cardinality index variables (IDs/Indices) to prevent optimization loops from leaking targets.
2. **Missing Ratio Imbalance:** Fill null distributions with localized statistical centers (Mean values for numbers, Modes for strings) to normalize feature space coordinates.
3. **Continuous Performance:** Study Area charts and Distribution Histograms regularly to audit longitudinal cohort skewness.`;
  };

  const getActiveReportContent = () => {
    switch (selectedReportId) {
      case 'ml':
        return generateMLReportContent();
      case 'brief':
        return generateBusinessReportContent();
      default:
        return generateEDAReportContent();
    }
  };

  const handleDownload = () => {
    const textStr = getActiveReportContent();
    const blob = new Blob([textStr], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AskDeepakAI-${selectedReportId}-Brief.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    setLogs((prev) => [...prev, `✓ Brief download completed successfully: AskDeepakAI-${selectedReportId}-Brief.md`]);
  };

  return (
    <div className="space-y-8" id="reports_module">
      {/* Dynamic Header Hub */}
      <div className="bg-slate-900/60 backdrop-blur-md rounded-2xl border border-slate-800 p-6 sm:p-8 shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-80 h-80 bg-indigo-550/5 bg-indigo-500/5 rounded-full blur-3xl pointer-events-none" />

        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6 relative z-10">
          <div>
            <span className="text-[10px] font-mono font-bold text-indigo-400 uppercase tracking-widest">PUBLICATION HUB</span>
            <h2 className="text-xl font-extrabold text-white tracking-tight mt-1 flex items-center gap-2">
              <BookOpen className="w-5.5 h-5.5 text-indigo-405 text-indigo-405 text-indigo-400" /> Executive Intelligence Hub
            </h2>
            <p className="text-xs text-slate-400 mt-1 max-w-xl">
              Preview, download, and compile standardized analytical reporting briefs suitable for product managers and stakeholders.
            </p>
          </div>
          <button
            onClick={handleDownload}
            className="bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs py-3 px-5 rounded-xl flex items-center gap-2 shadow-lg shadow-indigo-650/45 transition-all duration-300 self-start sm:self-auto cursor-pointer border-0"
          >
            <Download className="w-4 h-4 text-white shrink-0" /> DOWNLOAD BRIEF (.MD)
          </button>
        </div>

        {/* List of briefs bento */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-5 relative z-10 pt-5 border-t border-slate-800/80">
          {[
            { id: 'eda', tag: 'EXPLORATORY', title: 'Data Ingestion Diagnostic', desc: 'Synthesizes columns distributions, recommended model type, and target predictors.' },
            { id: 'ml', tag: 'PREDICTIVE', title: 'ML Pipeline Validation', desc: 'Validates hyperparameters trials, accuracy ratios, and feature importance.' },
            { id: 'brief', tag: 'MANAGEMENT', title: 'Business Stakeholder Brief', desc: 'High-level executive roadmap, missing ratios, and cohort insights.' }
          ].map((item) => (
            <button
              key={item.id}
              onClick={() => setSelectedReportId(item.id)}
              className={`text-left p-4.5 rounded-2xl border transition-all duration-300 relative group cursor-pointer ${
                selectedReportId === item.id
                  ? 'border-indigo-500/80 bg-indigo-950/20 shadow-lg shadow-indigo-550/10'
                  : 'border-slate-800 bg-slate-900/40 hover:bg-slate-900/80 hover:border-slate-700'
              }`}
            >
              <span className={`text-[8px] font-mono font-bold px-2.5 py-0.5 rounded-full tracking-widest uppercase border ${
                selectedReportId === item.id ? 'bg-indigo-500/15 text-indigo-400 border-indigo-500/20' : 'bg-slate-950/40 text-slate-400 border-slate-800'
              }`}>
                {item.tag}
              </span>
              <h4 className="font-extrabold text-white text-sm mt-3 group-hover:text-indigo-350 transition-colors">{item.title}</h4>
              <p className="text-[11px] text-slate-400 mt-1.5 leading-relaxed">{item.desc}</p>
            </button>
          ))}
        </div>
      </div>

      {/* Live Markdown Publication Editor */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <div className="lg:col-span-3 bg-slate-900/40 border border-slate-800 p-6 rounded-2xl shadow-xl animate-fade-in relative">
          <div className="flex items-center gap-2 mb-4 pb-2 border-b border-slate-805 border-slate-800">
            <Scroll className="w-5 h-5 text-indigo-405 text-indigo-400" />
            <h3 className="font-extrabold text-white text-base">Advisory Brief Workspace View</h3>
          </div>

          <div className="bg-slate-950 p-6 rounded-xl border border-slate-850 font-mono text-xs text-slate-300 whitespace-pre-line leading-relaxed shadow-inner overflow-hidden max-h-[500px] overflow-y-auto">
            {getActiveReportContent()}
          </div>
        </div>

        {/* Operational logs */}
        <div className="bg-slate-900/40 border border-slate-850 p-5 rounded-2xl text-xs text-slate-350 flex flex-col justify-between h-auto shadow-xl">
          <div className="space-y-4">
            <h3 className="text-[10px] font-bold uppercase tracking-widest text-[#5C6F84] flex items-center gap-2 font-mono">
              <Terminal className="w-4 h-4 text-emerald-450 text-emerald-450" /> Publication Logs
            </h3>
            <div className="bg-slate-950/50 p-3 h-[240px] rounded-xl border border-slate-850 font-mono text-[10px] text-emerald-400 space-y-1.5 overflow-y-auto shadow-inner">
              {logs.map((log, i) => (
                <div key={i} className="leading-relaxed">
                  {log}
                </div>
              ))}
            </div>
          </div>

          <div className="mt-6 border-t border-slate-800 pt-4 flex gap-2">
            <div className="w-9 h-9 bg-indigo-500/10 border border-indigo-500/25 text-indigo-400 rounded-xl flex items-center justify-center shrink-0">
              <Award className="w-4 h-4" />
            </div>
            <div>
              <p className="font-extrabold text-white text-[11px] font-mono leading-tight">Secure Sandbox File Transfer</p>
              <p className="text-[10px] text-slate-500 mt-0.5 leading-relaxed">Direct disk access compiled locally.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
